name: CI

on:
  push:
    branches: 'master'
  schedule:
    - cron: '0 15 * * 6'

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: Fetch latest compressed data 
        id: get_release
        uses: dsaltares/fetch-gh-release-asset@1.1.2
        with:
          repo: "dcampos/eb1911"
          file: "all.json.bz2"
          target: "data/all.json.bz2"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch latest compressed entry list 
        uses: dsaltares/fetch-gh-release-asset@1.1.2
        with:
          repo: "dcampos/eb1911"
          file: "entries.txt.bz2"
          target: "entries.txt.bz2"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set vars
        id: vars
        run: |
          echo "old_timestamp=$(echo '${{ steps.get_release.outputs.body }}' | head -1 | cut -f2 -d' ')" >> "$GITHUB_OUTPUT"
          echo "current_timestamp=$(date +'%Y%m%d%H%M%S')" >> "$GITHUB_OUTPUT"
          echo "${{ steps.get_release.outputs.body }}"

      - name: Create release tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.vars.outputs.current_timestamp }}',
              sha: context.sha
            })

      - name: Update articles
        id: update
        env:
          OLD_TIMESTAMP: ${{ steps.vars.outputs.old_timestamp }}
        run: |
          set -e
          ./eb1911.py update -n -i data/all.json.bz2 -o all.json -T $OLD_TIMESTAMP 2>&1 | tee output.txt
          bunzip2 -f entries.txt.bz2
          ./eb1911.py list | sort >|entries.txt
          ./eb1911.py fetch -n --missing --no-progress -i all.json --titles @entries.txt -o missing.json 2>&1 | tee -a output.txt
          cat missing.json >>all.json

      - name: Create slob dictionaries
        env:
          CUR_TIMESTAMP: ${{ steps.vars.outputs.current_timestamp }}
        run: |
          set -e
          ./eb1911.py slob --no-progress -i all.json -o eb1911.slob
          ./eb1911.py slob --no-progress -i all.json -o eb1911-gd.slob -g

      - name: Compress result
        run: |
          bzip2 -k all.json
          bzip2 -k entries.txt

      # - name: Create release tag
      #   uses: rickstaa/action-create-tag@v1
      #   with:
      #     tag: "${{ steps.vars.outputs.current_timestamp }}"
      #     message: "Latest release"

      # - name: Store commmand output
      #   run: |
      #     echo 'CMD_OUTPUT<<EOF' >> $GITHUB_ENV
      #     cat output.txt >> $GITHUB_ENV
      #     echo 'EOF' >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            all.json.bz2
            eb1911.slob
            eb1911-gd.slob
            entries.txt.bz2
            output.txt
          name: "1911 Encyclopædia Britannica"
          tag_name: ${{ steps.vars.outputs.current_timestamp }}
          # body: "Timestamp: ${{ steps.vars.outputs.current_timestamp }}"
          # body_path: output.txt
          body: |
            Timestamp: ${{ steps.vars.outputs.current_timestamp }}

      - name: Display the details
        run: |
          echo ${{ steps.get_release.outputs.version }}
          echo ${{ steps.get_release.outputs.name }}
          echo ${{ steps.get_release.outputs.body }}
          ls -l data/
